table Games

	/// Average meta score
	measure 'Avg Meta Score' = AVERAGE(Games[meta_score])
		formatString: 0.00

	/// Average user score
	measure 'Avg User Score' = AVERAGE(Games[user_score])
		formatString: 0.00

	column meta_score
		dataType: int64
		summarizeBy: sum
		sourceColumn: meta_score

	column title
		dataType: string
		summarizeBy: none
		sourceColumn: title

	column platform
		dataType: string
		summarizeBy: none
		sourceColumn: platform

	column date
		dataType: string
		summarizeBy: none
		sourceColumn: date

	column user_score
		dataType: double
		summarizeBy: sum
		sourceColumn: user_score

	column link
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: link

	column esrb_rating
		dataType: string
		summarizeBy: none
		sourceColumn: esrb_rating

	column developers
		dataType: string
		summarizeBy: none
		sourceColumn: developers

	column genres
		dataType: string
		summarizeBy: none
		sourceColumn: genres

	partition Games = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/yaylinda/nintendo-games-ratings/master/data.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"meta_score", Int64.Type}, {"title", type text}, {"platform", type text}, {"date", type text}, {"user_score", type number}, {"link", type text}, {"esrb_rating", type text}, {"developers", type text}, {"genres", type text}})
				in
				    #"Changed Type"

