table Games

	/// Average meta score
	measure 'Avg Meta Score' = AVERAGE(Games[Meta_score])
		formatString: 0.00

	/// Average user score
	measure 'Avg User Score' = AVERAGE(Games[User_score])
		formatString: 0.00

	/// Maximum meta score
	measure 'Max Meta Score' = MAX(Games[Meta_score])
		formatString: 0.00

	/// Maximum user score
	measure 'Max User Score' = MAX(Games[User_score])
		formatString: 0.00

	/// Total number of games published
	measure 'Games Published' = COUNTROWS(Games)
		formatString: #,0

	column Meta_score
		dataType: int64
		summarizeBy: none
		sourceColumn: meta_score

	/// Title of the game
	column Title
		dataType: string
		summarizeBy: none
		sourceColumn: title

	column Platform
		dataType: string
		isHidden: true
		summarizeBy: none
		sourceColumn: platform

	column PlatformKey
		dataType: int64
		isHidden: true
		summarizeBy: none
		sourceColumn: PlatformKey

	column Date
		dataType: string
		summarizeBy: none
		sourceColumn: date

	column User_score
		dataType: decimal
		summarizeBy: none
		sourceColumn: user_score

	column Esrb_rating
		dataType: string
		summarizeBy: none
		sourceColumn: esrb_rating

	column Developers
		dataType: string
		summarizeBy: none
		sourceColumn: developers

	column Genres
		dataType: string
		summarizeBy: none
		sourceColumn: genres

	partition Games = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/yaylinda/nintendo-games-ratings/master/data.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"meta_score", Int64.Type}, {"title", type text}, {"platform", type text}, {"date", type text}, {"user_score", type number}, {"link", type text}, {"esrb_rating", type text}, {"developers", type text}, {"genres", type text}}),
				    #"Selected Platform" = Table.SelectColumns(#"Promoted Headers", {"platform"}),
				    #"Removed Duplicates" = Table.Distinct(#"Selected Platform"),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Duplicates", each [platform] <> "TG16)" and [platform] <> "working title)"),
				    #"Sorted Rows" = Table.Sort(#"Filtered Rows", {{"platform", Order.Ascending}}),
				    #"Added Platform Index" = Table.AddIndexColumn(#"Sorted Rows", "PlatformKey", 1, 1, Int64.Type),
				    #"Merged Platform Lookup" = Table.NestedJoin(#"Changed Type", {"platform"}, #"Added Platform Index", {"platform"}, "PlatformLookup", JoinKind.LeftOuter),
				    #"Expanded Platform Lookup" = Table.ExpandTableColumn(#"Merged Platform Lookup", "PlatformLookup", {"PlatformKey"}, {"PlatformKey"})
				in
				    #"Expanded Platform Lookup"

