table Games

	/// Average meta score
	measure 'Avg Meta Score' = AVERAGE(Games[Meta_score])
		formatString: 0.00

	/// Average user score
	measure 'Avg User Score' = AVERAGE(Games[User_score])
		formatString: 0.00

	/// Maximum meta score
	measure 'Max Meta Score' = MAX(Games[Meta_score])
		formatString: 0.00

	/// Maximum user score
	measure 'Max User Score' = MAX(Games[User_score])
		formatString: 0.00

	column Meta_score
		dataType: int64
		summarizeBy: none
		sourceColumn: meta_score

	/// Title of the game
	column Title
		dataType: string
		summarizeBy: none
		sourceColumn: title

	column Platform
		dataType: string
		summarizeBy: none
		sourceColumn: platform

	column Date
		dataType: string
		summarizeBy: none
		sourceColumn: date

	column User_score
		dataType: decimal
		summarizeBy: none
		sourceColumn: user_score

	column Esrb_rating
		dataType: string
		summarizeBy: none
		sourceColumn: esrb_rating

	column Developers
		dataType: string
		summarizeBy: none
		sourceColumn: developers

	column Genres
		dataType: string
		summarizeBy: none
		sourceColumn: genres

	partition Games = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/yaylinda/nintendo-games-ratings/master/data.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"meta_score", Int64.Type}, {"title", type text}, {"platform", type text}, {"date", type text}, {"user_score", type number}, {"link", type text}, {"esrb_rating", type text}, {"developers", type text}, {"genres", type text}})
				in
				    #"Changed Type"

